---
apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: argocd-apps
  namespace: argocd

spec:
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/buddesree/2048.git
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-appps
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/buddesree/2048.git
    path: argocd-apps/base-apps
    targetRevision: main
  sources: []
  project: argocd-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
