---
apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: argocd-apps
  namespace: argocd

spec:
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/buddesree/2048.git
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
spec:
  project: argocd-apps
  source:
    repoURL: https://github.com/buddesree/2048.git
    targetRevision: main
    path: argocd-apps/base-apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true